### ISSUE TITLE
Algorithm is buggy and inefficient

### ISSUE THREAD

**Issue by MartyMcMartface** [RichardKnop/javascript-longest-increasing-subsequence#1]
- Fails on simple example where sequence is already ordered, returns null
- Fails in all cases where the longest sequence is at the end
- Keeps searching even when the longest possible sequence is found

**Comment by RichardKnop** [comment]
@MartyMcMartface Feel free to fix those issues. This was probably a solution to some interview puzzle or a coding challenge, don't remember exactly.

**Comment by MartyMcMartface** [comment]
I figured that but it was more a note to others not to use it. It's the top result when googling for javascript longest increasing subsequence so I'm probably not the first to find it and discover it doesn't work. Maybe you should consider removing it? Otherwise below is my fix but I'm not sure it's the most efficient either, it's just a hack of your algorithm to get it working.

``` javascript
function findLongestIncreasingSubsequence(sequence) {
    var proposals=[];
    var longestProposal=null;
    for (var i = 0; i < sequence.length; i++) {
        var proposal = [];
        proposal.push(sequence[i]);
        for (var j = i + 1; j < sequence.length; j++) {
            if (sequence[j] < proposal[proposal.length - 1]) break;
            proposal.push(sequence[j]);
        }
        proposals.push(proposal);
        if (longestProposal==null || proposal.length>longestProposal.length) longestProposal=proposal;
        if (longestProposal.length==sequence.length-i) return longestProposal;
    }
    return longestProposal;
}
```
